title: arkham's notebook
github_username: a-rkham
logo: /assets/img/logo.png
description: "<br>Anotações sobre hacking e segurança."
show_downloads: false
lang: pt-BR
google_analytics:
theme: jekyll-theme-minimal
kramdown:
  parse_block_html: true
  toc_levels: 1..3
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .bundle
