title: arkham notes
github_username: a-rkham
logo: /assets/img/logo.png
description: Anotações sobre hacking e segurança.
show_downloads: false
lang: pt-BR
google_analytics:
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .bundle
